In [3]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
X = np.array([
["good", "london"],
["good", "tokyo"],
["bad", "paris"],
["average", "so so"],
["good", "tokyo"]])
encoder = OrdinalEncoder()
encoder.fit_transform(X)
array([[2., 0.],
       [2., 3.],
       [1., 1.],
       [0., 2.],
       [2., 3.]])
encoder.categories_[array(['average', 'bad', 'good'], dtype='<U7'),array(['london', 'paris', 'so so', 'tokyo'], dtype='<U7')]

ImportError: cannot import name 'OrdinalEncoder' from 'sklearn.preprocessing' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [8]:
x,y=3)

TypeError: cannot unpack non-iterable int object

### Binary — convert each integer to binary digits. Each binary digit gets one column. Some info loss but fewer dimensions. Ordinal.
BaseN — Ordinal, Binary, or higher encoding. Nominal, ordinal. Doesn’t add much functionality. Probably avoid.
### Hashing — Like OneHot but fewer dimensions, some info loss due to collisions. Nominal, ordinal.

In [ ]:
 '''one needs to convert multi-class labels to binary labels (belong or does not belong to the class). 
 LabelBinarizer makes this process easy with the transform method.
 Binary can be thought of as a hybrid of one-hot and hashing encoders. Binary creates fewer features than one-hot, 
 while preserving some uniqueness of values in the the column. 
 It can work well with higher dimensionality ordinal data'''
    Here’s how it works:
The categories are encoded by OrdinalEncoder if they aren’t already in numeric form.
Then those integers are converted into binary code, so for example 5 becomes 101 and 10 becomes 1010
Then the digits from that binary string are split into separate columns. 
So if there are 4–7 values in an ordinal column then 3 new columns are created:
    one for the first bit, one for the second, and one for the third.
Each observation is encoded across the columns in its binary form.


In [16]:
# import the packages
import numpy as np
import pandas as pd 
import sklearn as sk
#import category_encoders as ce
from sklearn.preprocessing import LabelBinarizer
# make some data
df = pd.DataFrame({
 'color':["a", "b", "a", "c"], 
 'outcome':[1, 2, 3, 2]})

# split into X and y
X = df.drop('outcome', axis = 1)
y = df.drop('color', axis = 1)

# instantiate an encoder - here we use Binary()
ce_binary = ce.BinaryEncoder(cols = ['color'])

# fit and transform and presto, you've got encoded data
ce_binary.fit_transform(X, y)

NameError: name 'ce' is not defined

In [10]:
import sklearn as sk
from sklearn.preprocessing import CategoricalEncoder
#import sk.category_encoders 

ImportError: cannot import name 'CategoricalEncoder' from 'sklearn.preprocessing' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [53]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit([1, 2, 6, 8,4,4, 2])
LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)
lb.classes_


array([1, 2, 4, 6, 8])

In [50]:
lb.transform([1, 6])

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [24]:
lb = preprocessing.LabelBinarizer()
lb.fit_transform(['yes', 'no', 'no', 'yes'])

array([[1],
       [0],
       [0],
       [1]])

In [25]:
 import numpy as np
lb.fit(np.array([[0, 1, 1], [1, 0, 0]]))

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [26]:
LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)
lb.classes_

array([0, 1, 2])

In [27]:
lb.transform([0, 1, 2, 1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [3]:
import pandas as pd
mtch=pd.read_csv(r"C:\Users\HOME\Python\DataFiles\Match.csv")
mtch.tail(2)

Match_SK  match_id           Team1                    Team2 match_date  \
635       635   1082649  Mumbai Indians    Kolkata Knight Riders  5/19/2017   
636       636   1082650  Mumbai Indians  Rising Pune Supergiants  5/21/2017   

     Season_Year                                Venue_Name  \
635         2017                     M Chinnaswamy Stadium   
636         2017  Rajiv Gandhi International Stadium Uppal   

              City_Name Country_Name     Toss_Winner    match_winner  \
635           Bengaluru        India  Mumbai Indians  Mumbai Indians   
636  Hyderabad (Deccan)        India  Mumbai Indians  Mumbai Indians   

    Toss_Name Win_Type Outcome_Type  ManOfMach  Win_Margin  Country_id  
635     Field  wickets       Result  KV Sharma         6.0           1  
636       Bat      run       Result  KH Pandya         1.0           1

In [12]:
mtch.team1.unique()

AttributeError: 'DataFrame' object has no attribute 'team1'

In [8]:
dfnew = mtch.iloc[0:25,2:3]


In [13]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
z=lb.fit_transform(dfnew)
z

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [14]:
 pd.DataFrame(z)

0  1  2  3  4  5  6  7
0   0  0  0  0  0  0  0  1
1   0  0  0  1  0  0  0  0
2   0  0  1  0  0  0  0  0
3   0  0  0  0  0  1  0  0
4   0  0  0  0  1  0  0  0
5   0  0  0  0  0  0  1  0
6   0  1  0  0  0  0  0  0
7   1  0  0  0  0  0  0  0
8   0  1  0  0  0  0  0  0
9   0  0  0  1  0  0  0  0
10  0  0  0  0  0  0  0  1
11  1  0  0  0  0  0  0  0
12  0  0  0  0  0  1  0  0
13  0  0  0  1  0  0  0  0
14  0  0  0  0  0  0  0  1
15  0  0  0  0  1  0  0  0
16  0  0  1  0  0  0  0  0
17  0  1  0  0  0  0  0  0
18  0  0  0  0  0  0  1  0
19  1  0  0  0  0  0  0  0
20  0  1  0  0  0  0  0  0
21  0  0  0  1  0  0  0  0
22  0  0  0  0  0  1  0  0
23  0  0  0  0  0  0  1  0
24  0  0  0  0  0  0  0  1